// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type Problem struct {
	ID            string `json:"id"`
	Title         string `json:"title"`
	Description   string `json:"description"`
	TimeLimitMs   int32  `json:"time_limit_ms"`
	MemoryLimitMb int32  `json:"memory_limit_mb"`
}

type ProblemLanguageHarness struct {
	ProblemID   string `json:"problem_id"`
	Language    string `json:"language"`
	HarnessCode string `json:"harness_code"`
}

type TestCase struct {
	ID             int32  `json:"id"`
	ProblemID      string `json:"problem_id"`
	Input          string `json:"input"`
	ExpectedOutput string `json:"expected_output"`
	IsHidden       bool   `json:"is_hidden"`
}
