// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	// db/queries/problems.sql
	CreateProblem(ctx context.Context, arg CreateProblemParams) error
	CreateProblemLanguageHarness(ctx context.Context, arg CreateProblemLanguageHarnessParams) error
	CreateTestCase(ctx context.Context, arg CreateTestCaseParams) error
	DeleteProblem(ctx context.Context, id string) error
	DeleteProblemLanguageHarnessesByProblemID(ctx context.Context, problemID string) error
	DeleteTestCasesByProblemID(ctx context.Context, problemID string) error
	GetProblem(ctx context.Context, id string) (Problem, error)
	GetProblemLanguageHarnesses(ctx context.Context, problemID string) ([]GetProblemLanguageHarnessesRow, error)
	GetTestCases(ctx context.Context, problemID string) ([]GetTestCasesRow, error)
	UpdateProblem(ctx context.Context, arg UpdateProblemParams) error
}

var _ Querier = (*Queries)(nil)
